import type { CognitiveTrace } from './cognitive-state';

/**
 * OutputModality
 *
 * Mirrors the input surface — every modality that can receive a response.
 */
export type OutputModality =
  'text' | 'voice' | 'vision' | 'cli' | 'api' | 'multimodal';

/**
 * BrainOutput
 *
 * The final product of the cognitive pipeline, returned by BrainV2Service.
 * Contains the natural-language response plus observability data.
 */
export interface BrainOutput {
  /** Mirrors sessionId from BrainInput for correlation. */
  sessionId: string;

  /** The natural-language response generated by the Language Generator. */
  content: string;

  /** Modality of the response surface (usually mirrors input modality). */
  modality: OutputModality;

  /** Total wall-clock latency from input receipt to response. */
  latencyMs: number;

  /**
   * Full cognitive trace — records which modules activated, their
   * individual latencies, and decision rationale.
   * Used for observability, self-improvement, and debugging.
   */
  cognitiveTrace: CognitiveTrace;

  /** Wall-clock time at which the response was finalized. */
  respondedAt: Date;
}
