services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: jarvis-n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      TZ: Asia/Kolkata

      N8N_HOST: 192.168.31.140
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_SECURE_COOKIE: "false"

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: jarvis-postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: jarvis
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
     # N8N_RESTRICT_FILE_ACCESS_TO: /home/node/.n8n-files:/data/knowledge

    env_file:
      - ../.env

    volumes:
      - ../data/n8n:/home/node/.n8n
      - ../data/knowledge:/data/knowledge

    networks:
      - jarvis

networks:
  jarvis:
    external: true
    name: jarvis-network
