export enum MemoryEvents {
  CONVERSATION_MESSAGE_CREATED = 'conversation.message.created',
  CONVERSATION_MESSAGE_UPDATED = 'conversation.message.updated',
  MEMORY_CREATED = 'memory.created',
  MEMORY_UPDATED = 'memory.updated',
  MEMORY_ARCHIVED = 'memory.archived',
  MEMORY_DELETED = 'memory.deleted',
  MEMORY_ACCESSED = 'memory.accessed',
  EPISODE_CREATED = 'episode.created',
  RELATIONSHIP_CREATED = 'relationship.created',
  GOAL_UPDATED = 'goal.updated',
  PREFERENCE_CHANGED = 'preference.changed',
  MEMORY_FACT_EXTRACTED = 'memory.fact.extracted',
  MEMORY_RELATIONSHIP_EXTRACTED = 'memory.relationship.extracted',
  MEMORY_PREFERENCE_EXTRACTED = 'memory.preference.extracted',
  MEMORY_GOAL_EXTRACTED = 'memory.goal.extracted',
  MEMORY_EPISODE_EXTRACTED = 'memory.episode.extracted',
  MEMORY_PROCEDURE_EXTRACTED = 'memory.procedure.extracted',
  MEMORY_PROJECT_EXTRACTED = 'memory.project.extracted',
  MEMORY_DEVICE_EXTRACTED = 'memory.device.extracted',
}
