import { BrainCapability } from '../enums/brain-capability.enum';

/**
 * Identifies a single unit of work routed through the Brain.
 *
 * A task ID is opaque to the Brain itself — it is generated by whichever
 * caller initiates the task (e.g. a conversation turn, a scheduled job,
 * an automation trigger) and is threaded through unchanged so results,
 * logs, and errors can be correlated back to their origin.
 */
export type BrainTaskId = string;

/**
 * Arbitrary, module-defined payload data for a task.
 *
 * Left as an open record rather than a fixed shape: the Brain contracts
 * must not need to change every time a new module introduces a new kind
 * of task payload. Individual modules are responsible for validating
 * and narrowing this at their own boundary.
 */
export type BrainTaskPayload = Record<string, unknown>;

/**
 * Priority hint for scheduling/ordering. Advisory only — the contracts
 * make no guarantee about how (or whether) any given implementation
 * uses this value.
 */
export type BrainTaskPriority = 'LOW' | 'NORMAL' | 'HIGH' | 'CRITICAL';

/**
 * A single unit of work that can be routed to one or more Brain modules.
 */
export interface BrainTask {
  id: BrainTaskId;

  /**
   * The capability this task requires. Used for routing a task to the
   * module(s) that declare support for it via BrainModule.capabilities.
   */
  capability: BrainCapability;

  /**
   * Module-defined payload. See BrainTaskPayload.
   */
  payload: BrainTaskPayload;

  priority?: BrainTaskPriority;

  /**
   * Optional correlation ID for tracing a task across module boundaries
   * (e.g. linking a Vision detection task back to the Voice interaction
   * that triggered it). Distinct from `id`, which identifies this task
   * specifically.
   */
  correlationId?: string;

  /**
   * Arbitrary caller-supplied context. Intentionally untyped for the
   * same reason as BrainTaskPayload — this contract must not need to
   * change as new context shapes are introduced by future modules.
   */
  context?: Record<string, unknown>;
}
